# (1)
print("aoi orio")
# (2)
name = input("あなたの名前を教えてください: ")
print("こんにちは。" + name + "さん")
# (3)
import random, math
randasan = random.uniform(10, 1000)
randkun = random.uniform(100, 500)
print("何が出るかな？" + str(math.floor((randasan)) * math.floor(randkun)))
# (4)
numberkun = int(input("好きな数字を教えてください: "))
numbersan = int(input("2番目に好きな数字を教えてください: "))
print(numberkun + numbersan)