import random
# 1)
print("(1)")
print("moriyoshi")
# 2)
print("(2)")
name = input("名前を入力してください ")
print("こんにちは。" + name + "さん")
# 3)
print("(3)")
print(random.randint(1, 10) * random.randint(1, 10))
# 4)
first = int(input("数字を入力してください "))
second = int(input("数字を入力してください "))
print(first + second)
