# 1)
print("(1)")
print("moriyoshi")
# 2)
print("(2)")
print("moriyoshi")
print("モリヨシ")
print(15)
# 3)
print("(3)")
weight = 55
height = 170
print("moriyoshi")
print("私の体重は" + str(weight) + "kgです")
print("私の身長は" + str(height) + "cmです")
print("私のBMIは" + str(round(weight / ((height/100) ** 2))) + "です")
# 4)
print("(4)")
print(12+15)
# 5)
print("(5)")
weight = int(input("体重を入力してください"))
height = int(input("身長を入力してください"))
print("あなたの体重は" + str(weight) + "kgです")
print("あなたの身長は" + str(height) + "cmです")
